name: Register Package to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Build and push Docker image to Google Artifact Registry
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/creative-spaces/creative-spaces:latest .
        docker push ghcr.io/${{ github.repository_owner }}/creative-spaces/creative-spaces:latest
        docker push europe-west2-docker.pkg.dev/creativelandscapes/creative-spaces/creative-spaces:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy creative-spaces-service \
          --image=europe-west2-docker.pkg.dev/creativelandscapes/creative-spaces/creative-spaces:latest \
          --platform=managed \
          --region=europe-west2 \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=1 \
          --max-instances=5 \
          --allow-unauthenticated \
          --quiet
